name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: de_files
          path: public/de/
      - uses: actions/upload-artifact@v4
        with:
          name: en_files
          path: public/en/

  publish_de:
    needs: build
    uses: ./.github/workflows/publish.yml
    with:
      repository: renekaesler/renekaesler.de
      files: de_files
    secrets: inherit

  publish_en:
    needs: build
    uses: ./.github/workflows/publish.yml
    with:
      repository: renekaesler/renekaesler.com
      files: en_files
    secrets: inherit
