name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: public

  publish_en:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
        with:
          path: dest
          ref: main
          repository: renekaesler/renekaesler.com    
      - uses: actions/download-artifact@v4
        with:
          path: public
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: |
          cp -rvT public/en/ dest
          rm -rf public
          git add .
          git commit -m 'Auto Publish'
      - run: git push
      