name: publish

on:
  workflow_call:
    inputs:
      repository:
        description: 'repository that hosts the website'
        required: true
        type: string
      site:
        description: 'website artifacts'
        required: true
        type: string
    secrets:
      ACTIONS_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: main
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - run: rm -rf _site
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.site }}
          path: _site
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add _site
          git diff-index --quiet HEAD || git commit -m 'Auto Publish:  ${{ inputs.repository }}'
          git push
